apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: home
      defaultBucket: Home Assistant
      tlsSkipVerify: true
    secureJsonData:
      token: _REDACTED_
